# Generated by Django 4.2.1 on 2024-07-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion_producto', models.TextField()),
                ('cantidad_producto', models.IntegerField()),
                ('precio_producto', models.FloatField()),
                ('imagen_producto', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_aprobado', models.CharField(max_length=255)),
                ('estado_producto_aprobado', models.CharField(max_length=50)),
            ],
        ),
    ]
