# Generated by Django 4.2.1 on 2024-07-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=250),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre Desconocido', max_length=25),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
